server:
  port: 8083
logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: msa-report

  jackson:
    default-property-inclusion: non_null

  services:
    msa-client:
      url: http://localhost:8080
    msa-account:
      url: http://localhost:8081
    msa-movement:
      url: http://localhost:8082