server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: msa-report

  jackson:
    default-property-inclusion: non_null

  services:
    msa-client:
      url: ${MSA_CLIENT_URL:http://localhost:8080}
    msa-account:
      url: ${MSA_ACCOUNT_URL:http://localhost:8081}
    msa-movement:
      url: ${MSA_MOVEMENT_URL:http://localhost:8082}

webclient:
  timeout:
    connect: ${WEBCLIENT_CONNECT_TIMEOUT:5000}
    read: ${WEBCLIENT_READ_TIMEOUT:15000}
    write: ${WEBCLIENT_WRITE_TIMEOUT:15000}
