logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: msa-report

  jackson:
    default-property-inclusion: non_null

  services:
    msa-client:
      url: ${MSA_CLIENT_URL:http://msa-client:8080}
    msa-account:
      url: ${MSA_ACCOUNT_URL:http://msa-account:8080}
    msa-movement:
      url: ${MSA_MOVEMENT_URL:http://msa-movement:8080}

webclient:
  timeout:
    connect: ${WEBCLIENT_CONNECT_TIMEOUT:5000}
    read: ${WEBCLIENT_READ_TIMEOUT:15000}
    write: ${WEBCLIENT_WRITE_TIMEOUT:15000}
