logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: msa-report

  jackson:
    default-property-inclusion: non_null

  r2dbc:
    url: r2dbc:pool:mssql://sqlserver:1433/challenge
    username: sa
    password: Holamundo11*

  services:
    msa-client:
      url: http://msa-client:8080
    msa-account:
      url: http://msa-account:8081
    msa-movement:
      url: http://msa-movement:8082