openapi: 3.0.0
info:
  version: 1.0.1
  title: Movement Service
  description: Service that performs movement CRUD
  contact:
    name: Byron Delgado
    email: bydelgad@pichincha.com
servers:
  - url: http://localhost:8080
    description: Localhost

paths:
  /movimientos:
    get:
      tags:
        - Movements
      summary: Obtain the movements
      description: Returns the list of movements.
      parameters:
        - in: query
          name: accountId
          required: false
          description: account Id
          schema:
            type: integer
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponseDto'
        "500":
          $ref: "#/components/responses/500"
        "504":
          $ref: "#/components/responses/504"
    post:
      tags:
        - Movements
      summary: Create a new movement
      description: Returns the new movement.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRequestDto'
      operationId: save
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponseDto'
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
        "504":
          $ref: "#/components/responses/504"
components:
  responses:
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorsDto"
          example:
            title: Missing mandatory fields.
            detail: The input fields are not correct
            errors:
              - message: Bad Request
                businessMessage: The xyz field is mandatory
            instance: "022"
            type: /v1/name/pathSuffix
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorsDto"
          example:
            title: Not Found
            detail: Path not found
            instance: "404"
            type: /v1/name/pathSuffix
    "500":
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorsDto"
          example:
            title: Internal Server
            detail: An internal error occurred, we are reviewing it.
            instance: "0000"
            type: /v1/name/pathSuffix
            #resource: /xx/v1/yyy
    "504":
      description: Gateway Timeout
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorsDto"
          example:
            title: Gateway Timeout. Request timeout exceeded. If it happens repeatedly, consider reducing the request complexity.
            detail: Gateway connection problems.
            instance: "504"
            type: /v1/name/pathSuffix
  schemas:
    MovementResponseDto:
      type: object
      properties:
        movementId:
          type: integer
          description: Movement Id
          nullable: false
          example: 1
        date:
          type: string
          description: Date
          nullable: false
          example: "12/03/2024"
        type:
          type: string
          description: Movement Type
          nullable: false
          enum:
            - Credito
            - Debito
          example: Credito
        value:
          type: number
          format: double
          description: Value
          nullable: false
          example: 150.35
        balance:
          type: number
          format: double
          description: Balance
          nullable: false
          example: 350.35
        accountId:
          type: integer
          description: Account Id
          nullable: false
          example: 1
    MovementRequestDto:
      type: object
      properties:
        date:
          type: string
          description: Date of movement
          nullable: false
          example: "12/03/2024"
        type:
          type: string
          description: Movement Type
          nullable: false
          enum:
            - Credito
            - Debito
          example: Credito
        value:
          type: number
          format: double
          description: Value
          nullable: false
          example: 150.35
        balance:
          type: number
          format: double
          description: Balance
          nullable: false
          example: 350.35
        accountId:
          type: integer
          description: Account Id
          nullable: false
          example: 1
      required:
        - numberAccount
        - value
        - accountId
    ErrorDto:
      type: object
      properties:
        message:
          type: string
          description: Detail message
          nullable: false
        businessMessage:
          type: string
          description: Business error message
          nullable: false
    ErrorsDto:
      type: object
      properties:
        title:
          type: string
          description: Technical error message
          nullable: false
          example: Missing mandatory fields.
        detail:
          type: string
          description: Message to display to the client
          nullable: false
          example: The input fields are not correct
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDto'
        instance:
          type: string
          description: Error catalog code
          nullable: false
          example: "022"
        type:
          type: string