server:
  port: 8081

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: msa-account

  jackson:
    default-property-inclusion: non_null

  r2dbc:
    url: r2dbc:pool:mssql://localhost:1433/challenge
    username: sa
    password: Holamundo11*

  services:
    msa-client:
      url: http://localhost:8080