logging:
  level:
    org.springframework.data.r2dbc: DEBUG
spring:
  application:
    name: msa-movement

  jackson:
    default-property-inclusion: non_null

  r2dbc:
    url: ${DB_URL:r2dbc:pool:mssql://sqlserver:1433/challenge}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:Holamundo11*}

  services:
    msa-account:
      url: ${MSA_ACCOUNT_URL:http://msa-account:8080}

webclient:
  timeout:
    connect: ${WEBCLIENT_CONNECT_TIMEOUT:5000}
    read: ${WEBCLIENT_READ_TIMEOUT:10000}
    write: ${WEBCLIENT_WRITE_TIMEOUT:10000}
